spring:
  datasource:
    url: jdbc:mysql://192.168.108.129:3306/animalkindom?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
  mvc:
    dispatch-options-request: true
  redis:
    host: 192.168.108.129
    port: 6379

server:
  compression.enabled: true
  compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript

system:
  env: dev

game:
  maxMapNumber: 4000
  initMapCapacity: 400
  #移动
  mapMoveInterval: 10
  moveVigourCost: 30
  moveSatietyCostPercent: 0.2
  #睡眠
  sleepVigourRecoverMinInterval: 300 #每5分钟恢复精力/消耗饱食度一次
  sleepVigourRecover: 1 #每次恢复1点
  sleepSatietyCost: 0.001 #每次消耗千分之一




